/**
 * Generated by tsnapi — public API snapshot of `x6-vue-html-shape`
 */
// #region Interfaces
export interface MountedVueInstance {
  app: App<Element>;
  root: HTMLElement;
  component: Component;
}
export interface RegisterVueHtmlNodeOptions {
  shape: string;
  component: Component;
  primer?: Primer;
  overwrite?: boolean;
}
export interface RegisterVueHtmlShapeOptions {
  shape?: string;
  compatibleShapeName?: boolean;
  overwrite?: boolean;
  primer?: Primer;
  component?: Component;
}
export interface ShapeRegistryItem {
  component?: Component;
}
export interface SyncOptions {
  throttle?: number;
  useAnimationFrame?: boolean;
}
export interface VueHtmlLayerState {
  root: HTMLElement;
  graph: Graph;
  nodes: Map<string, HTMLElement>;
}
export interface VueHtmlShapePluginOptions extends RegisterVueHtmlShapeOptions {
  injectStyle?: boolean;
}
export interface VueHtmlShapeProperties {
  markup?: unknown;
  attrs?: Record<string, unknown>;
  component?: Component;
  primer?: Primer;
  htmlClassName?: string;
  htmlStyle?: Record<string, string>;
  interactive?: boolean;
  scaleContent?: boolean;
  syncVisible?: boolean;
  safariSafe?: boolean;
  getContainer?: (_: Graph, _: Node) => HTMLElement;
  props?: Record<string, unknown>;
  keepAliveOnUpdate?: boolean;
}
export interface VueShapeComponentProps<N extends Node = Node> {
  node: N;
  graph: Graph;
}
export interface VueShapeContext<N extends Node = Node> {
  node: N;
  graph: Graph;
}
export interface VueShapeProvide<N extends Node = Node> {
  getNode: () => N;
  getGraph: () => Graph;
}
// #endregion

// #region Types
export type Primer = 'rect' | 'circle' | 'path' | 'ellipse' | 'polygon' | 'polyline';
export type VueShapeComponent<N extends Node = Node> = Component<VueShapeComponentProps<N>>;
// #endregion

// #region Classes
export declare class VueHtmlShapeView extends NodeView {
  static action: never;
  private app;
  private htmlRoot;
  private contentRoot;
  private mountedComponent;
  private componentProps;
  private htmlStyle;
  static geometryAction: never;
  confirmUpdate(_: number): number;
  protected getNodeProperties(): VueHtmlShapeProperties;
  protected getComponent(): Component | undefined;
  protected ensureHtmlRoot(): {
    contentRoot: HTMLDivElement;
    htmlRoot: HTMLDivElement;
  };
  protected renderVueComponent(): void;
  protected updateHtmlAttributes(): void;
  updateHtmlPosition(): void;
  updateHtmlVisible(): void;
  protected unmountVueComponent(): void;
  protected removeHtmlRoot(): void;
  onMouseDown(_: Dom.MouseDownEvent, _: number, _: number): void;
  unmount(): this;
}
// #endregion

// #region Functions
export declare function clearVueShapeComponents(): void;
export declare function createVueHtmlShapePlugin(_?: VueHtmlShapePluginOptions): Plugin;
export declare function createVueHtmlTeleport(_: Graph): Component;
export declare function ensureVueHtmlLayer(_: Graph): HTMLElement;
export declare function getVueShapeComponent(_: string): Component | undefined;
export declare function install(_: App, _?: VueHtmlShapePluginOptions): void;
export declare function registerVueHtmlNode(_: RegisterVueHtmlNodeOptions): void;
export declare function registerVueHtmlShapeNode(_?: RegisterVueHtmlShapeOptions): void;
export declare function registerVueShapeComponent(_: string, _: Component): void;
export declare function removeVueHtmlLayer(_: Graph): void;
export declare function setupVueHtmlShapeSync(_: Graph, _?: SyncOptions): () => void;
export declare function shouldStopGraphMouseDown(_: EventTarget | null): boolean;
export declare function unregisterVueShapeComponent(_: string): void;
export declare function useX6NodeData<T = unknown>(_: Node): ShallowRef<T>;
// #endregion

// #region Variables
export declare const COMPAT_SHAPE_NAME: string;
export declare const DEFAULT_SHAPE_NAME: string;
export declare const DEFAULT_VIEW_NAME: string;
export declare const HTML_LAYER_CLASS: string;
export declare const HTML_NODE_CLASS: string;
export declare const HTML_NODE_CONTENT_CLASS: string;
export declare const STYLE_ID: string;
// #endregion

// #region Default Export
declare function _default(_: App, _?: VueHtmlShapePluginOptions): void;
export default _default
// #endregion